### ISSUE TITLE
VarDict bug after realignment

### ISSUE THREAD

**Issue by mathiasbio** [Clinical-Genomics/BALSAMIC#1271]
**Describe the bug**

This error has been thrown quite randomly by VarDict and causes a crash. After restarting it succeeds. So it seems quite random.
I saw it previously in this PR https://github.com/Clinical-Genomics/BALSAMIC/pull/1176 but misinterpreted the error. Looking at it today it seems to be related to the realignment which was introduced for TGA in this PR, and which has been mentioned in this issue on VarDict as being related to realignment: https://github.com/AstraZeneca-NGS/VarDictJava/issues/341

```
There was Exception while processing variant on 70121684 on region 17:70119553-70122691. The processing will be continued from the next variant.
java.lang.IllegalArgumentException
	at java.nio.Buffer.position(Buffer.java:244)
	at htsjdk.samtools.MemoryMappedFileBuffer.skipBytes(MemoryMappedFileBuffer.java:49)
```

I think we short revert the TGA workflow to not do realignment as this is what we were doing before, and since we have already discussed removing realignment for all workflows, this seems like the safest and easiest choice. We can keep it for WGS for now.

**To Reproduce**

Seems quite random, and is therefore difficult to reproduce reliably.

**Expected behavior**

**If workflow, which rules**
If possible, and using the Snakemake workflows, the name of the affected rules and workflows.

**Screenshots**

**Version (please complete the following information):**
`balsamic --version` development branch (2023-10-02)

**Additional context**

**Comment by mathiasbio** [comment]
Solved with: https://github.com/Clinical-Genomics/BALSAMIC/pull/1272
