### ISSUE TITLE
gsutil's dependency cryptography requires setuptools_rust and it is missing

### ISSUE THREAD

**Issue by hassanfa** [Clinical-Genomics/BALSAMIC#549]
**Describe the bug**
gsutil's dependency cryptography requires setuptools_rust and it is missing

```
            =============================DEBUG ASSISTANCE==========================
            If you are seeing an error here please try the following to
            successfully install cryptography:
    
            Upgrade to the latest pip and try again. This will fix errors for most
            users. See: https://pip.pypa.io/en/stable/installing/#upgrading-pip
            =============================DEBUG ASSISTANCE==========================
    
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-usdhuiqz/cryptography/setup.py", line 14, in <module>
        from setuptools_rust import RustExtension
    ModuleNotFoundError: No module named 'setuptools_rust'
```

**To Reproduce**
`pip install -U -r requirements.txt -e .`

**Expected behavior**
pip to install without issues.

**If workflow, which rules**
N/A

**Screenshots**
N/A

**Version (please complete the following information):**
`6.0.4`

**Additional context**

**Comment by hassanfa** [comment]
Problem is 3.4 cryptography where they added rust-tools:

https://github.com/pyca/cryptography/blob/master/CHANGELOG.rst#34---2021-02-07

Rolling back cryptography to <3.4
