### ISSUE TITLE
MultiQC broke after adding new stats

### ISSUE THREAD

**Issue by hassanfa** [Clinical-Genomics/BALSAMIC#744]
**Describe the bug**
MultiQC cannot parse bcftools stats file properly:
```
[ERROR  ]         multiqc : Oops! The 'bcftools' MultiQC module broke... 
  Please copy the following traceback and report it at https://github.com/ewels/MultiQC/issues 
  If possible, please include a log file that triggers the error - the last file found was:
    ============================================================
Module bcftools raised an exception: Traceback (most recent call last):
  File "/opt/conda/envs/align_qc/lib/python3.9/site-packages/multiqc/multiqc.py", line 569, in run
    output = mod()
  File "/opt/conda/envs/align_qc/lib/python3.9/site-packages/multiqc/modules/bcftools/bcftools.py", line 37, in __init__
    n['stats'] = self.parse_bcftools_stats()
  File "/opt/conda/envs/align_qc/lib/python3.9/site-packages/multiqc/modules/bcftools/stats.py", line 115, in parse_bcftools_stats
    quality = float(s[2].strip())
ValueError: could not convert string to float: '.'
```

**To Reproduce**
Running MultiQC lower than version 1.10

**Expected behavior**
MultiQC to finish properly

**If workflow, which rules**
`balsamic.smk`

**Screenshots**
None.

**Version (please complete the following information):**
`8.0.2`

**Additional context**
None.

**Comment by hassanfa** [comment]
done!
